- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy HTML file
      copy:
        content: "<html><body><h1>Hello, World!</h1></body></html>"
        dest: /var/www/html/index.html

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
